## Тема “Создание признакового пространства”

#### Продолжим обработку данных с Твиттера.

In [15]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
# Загрузим твиты

In [4]:
df = pd.read_pickle("Practice_1.pkl")
df.head()

,id,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...","[father, dysfunct, selfish, drag, kid, dysfunc...","[father, dysfunctional, selfish, drag, kid, dy..."
1,2,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...","[thank, lyft, credit, use, caus, offer, wheelc...","[thanks, lyft, credit, use, cause, offer, whee..."
2,3,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]","[bihday, majesti]","[bihday, majesty]"
3,4,model love you take with you all the time in ur,"[model, love, you, take, with, you, all, the, ...","[model, love, take, time, ur]","[model, love, take, time, ur]","[model, love, take, time, ur]"
4,5,factsguide society now motivation,"[factsguide, society, now, motivation]","[factsguide, society, motivation]","[factsguid, societi, motiv]","[factsguide, society, motivation]"

1. Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.

    • Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
    
    • Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
    
    • Исключим стоп-слова с помощью stop_words='english'.
    
    • Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью 
    CountVectorizer.get_feature_names().

In [5]:
# Преобразуем данные
df['tweet_stemmed'] = df['tweet_stemmed'].apply(lambda tokens: ' '.join(tokens))
df['tweet_lemmatized'] = df['tweet_lemmatized'].apply(lambda tokens: ' '.join(tokens))
df.head()

,id,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...",father dysfunct selfish drag kid dysfunct run,father dysfunctional selfish drag kid dysfunct...
1,2,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...",thank lyft credit use caus offer wheelchair va...,thanks lyft credit use cause offer wheelchair ...
2,3,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]",bihday majesti,bihday majesty
3,4,model love you take with you all the time in ur,"[model, love, you, take, with, you, all, the, ...","[model, love, take, time, ur]",model love take time ur,model love take time ur
4,5,factsguide society now motivation,"[factsguide, society, now, motivation]","[factsguide, society, motivation]",factsguid societi motiv,factsguide society motivation

In [6]:
count_vectorizer = CountVectorizer(ngram_range=(1, 1), # quantity colocations
                                   analyzer='word', # 'char'
                                   binary=False, # or all quantity
                                   tokenizer=str.split, 
                                   stop_words="english", 
                                   max_df=0.9, 
                                   max_features=1000)
count_vectorizer

CountVectorizer(max_df=0.9, max_features=1000, stop_words='english',
                tokenizer=<method 'split' of 'str' objects>)

In [7]:
#Создаем the Bag-of-Words модель для tweet_stemmed
bag_of_words_stemmed = count_vectorizer.fit_transform(df['tweet_stemmed'])
bag_of_words_stemmed

<49159x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 205863 stored elements in Compressed Sparse Row format>

In [8]:
# Отобразим Bag-of-Words модель как DataFrame
columns = count_vectorizer.get_feature_names()
stemmed_count = pd.DataFrame(bag_of_words_stemmed.toarray(), columns=columns)
stemmed_count.head()

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yeah,year,yesterday,yo,yoga,york,young,youtub,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
# Создаем the Bag-of-Words модель для tweet_lemmatized
bag_of_words_lemmatized = count_vectorizer.fit_transform(df['tweet_lemmatized'])
bag_of_words_lemmatized

<49159x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 190672 stored elements in Compressed Sparse Row format>

In [14]:
# Отобразим Bag-of-Words модель как DataFrame
columns = count_vectorizer.get_feature_names()
lemmatized_count = pd.DataFrame(bag_of_words_lemmatized.toarray(), columns=columns)
lemmatized_count.head()

,able,absolutely,account,act,action,actor,actually,adapt,add,adventure,...,year,yes,yesterday,yo,yoga,york,young,youtube,yr,yummy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

2. Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform().
Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.

    • Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
    
    • Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
    
    • Исключим стоп-слова с помощью stop_words='english'.
    
    • Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().

In [16]:
tfidf_vectorizer = CountVectorizer(ngram_range=(1, 1), # quantity colocations
                                   analyzer='word', # 'char'
                                   binary=False, # or all quantity
                                   tokenizer=str.split, 
                                   stop_words="english", 
                                   max_df=0.9, 
                                   max_features=1000)
tfidf_vectorizer

CountVectorizer(max_df=0.9, max_features=1000, stop_words='english',
                tokenizer=<method 'split' of 'str' objects>)

In [17]:
# Создаем the Bag-of-Words модель для tweet_stemmed
tfidf_vectorizer_stemmed = tfidf_vectorizer.fit_transform(df['tweet_stemmed'])
tfidf_vectorizer_stemmed

<49159x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 205863 stored elements in Compressed Sparse Row format>

In [18]:
# Отобразим Bag-of-Words модель как DataFrame
columns = tfidf_vectorizer.get_feature_names()
stemmed_tfidf = pd.DataFrame(tfidf_vectorizer_stemmed.toarray(), columns=columns)
stemmed_tfidf.head()

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yeah,year,yesterday,yo,yoga,york,young,youtub,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
# Создаем the Bag-of-Words модель для tweet_lemmatized
tfidf_vectorizer_lemmatized = count_vectorizer.fit_transform(df['tweet_lemmatized'])
tfidf_vectorizer_lemmatized

<49159x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 190672 stored elements in Compressed Sparse Row format>

In [20]:
# Отобразим Bag-of-Words модель как DataFrame
columns = tfidf_vectorizer.get_feature_names()
lemmatized_tfidf = pd.DataFrame(tfidf_vectorizer_lemmatized.toarray(), columns=columns)
lemmatized_tfidf.head()

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yeah,year,yesterday,yo,yoga,york,young,youtub,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

3. Натренируем gensim.models.Word2Vec модель на наших данных.

    • Тренировать будем на токенизированных твитах combine_df['tweet_token']
    
    • Установим следующие параметры: size=200, window=5, min_count=2, sg = 1, hs = 0, negative = 10, workers= 32, seed = 34.
        
    • Используем функцию train() с параметром total_examples равным длине combine_df['tweet_token'], количество epochs установим 20.